


with s1 as (
SELECT 2013 as year ,[DESY_SORT_KEY],[CLAIM_NO], (isnull([ICD_DGNS_CD1],'')+'^'+      isnull([ICD_DGNS_CD2],'')+'^'+      isnull([ICD_DGNS_CD3],'')+'^'+      isnull([ICD_DGNS_CD4],'')+'^'+      isnull([ICD_DGNS_CD5],'')+'^'+      isnull([ICD_DGNS_CD6],'')+'^'+      isnull([ICD_DGNS_CD7],'')+'^'+      isnull([ICD_DGNS_CD8],'')+'^'+      isnull([ICD_DGNS_CD9],'')+'^'+      isnull([ICD_DGNS_CD10],'')+'^'+      isnull([ICD_DGNS_CD11],'')+'^'+      isnull([ICD_DGNS_CD12],'')+'^'+      isnull([ICD_DGNS_CD13],'')+'^'+      isnull([ICD_DGNS_CD14],'')+'^'+      isnull([ICD_DGNS_CD15],'')+'^'+      isnull([ICD_DGNS_CD16],'')+'^'+      isnull([ICD_DGNS_CD17],'')+'^'+      isnull([ICD_DGNS_CD18],'')+'^'+      isnull([ICD_DGNS_CD19],'')+'^'+      isnull([ICD_DGNS_CD20],'')+'^'+      isnull([ICD_DGNS_CD21],'')+'^'+      isnull([ICD_DGNS_CD22],'')+'^'+      isnull([ICD_DGNS_CD23],'')+'^'+      isnull([ICD_DGNS_CD24],'')+'^'+      isnull([ICD_DGNS_CD25],'')) as dxall  FROM [CAT1].[cms].[out_claimsj_2013]
union SELECT 2013 as year ,[DESY_SORT_KEY],[CLAIM_NO], (isnull([ICD_DGNS_CD1],'')+'^'+      isnull([ICD_DGNS_CD2],'')+'^'+      isnull([ICD_DGNS_CD3],'')+'^'+      isnull([ICD_DGNS_CD4],'')+'^'+      isnull([ICD_DGNS_CD5],'')+'^'+      isnull([ICD_DGNS_CD6],'')+'^'+      isnull([ICD_DGNS_CD7],'')+'^'+      isnull([ICD_DGNS_CD8],'')+'^'+      isnull([ICD_DGNS_CD9],'')+'^'+      isnull([ICD_DGNS_CD10],'')+'^'+      isnull([ICD_DGNS_CD11],'')+'^'+      isnull([ICD_DGNS_CD12],'')+'^'+      isnull([ICD_DGNS_CD13],'')+'^'+      isnull([ICD_DGNS_CD14],'')+'^'+      isnull([ICD_DGNS_CD15],'')+'^'+      isnull([ICD_DGNS_CD16],'')+'^'+      isnull([ICD_DGNS_CD17],'')+'^'+      isnull([ICD_DGNS_CD18],'')+'^'+      isnull([ICD_DGNS_CD19],'')+'^'+      isnull([ICD_DGNS_CD20],'')+'^'+      isnull([ICD_DGNS_CD21],'')+'^'+      isnull([ICD_DGNS_CD22],'')+'^'+      isnull([ICD_DGNS_CD23],'')+'^'+      isnull([ICD_DGNS_CD24],'')+'^'+      isnull([ICD_DGNS_CD25],'')) as dxall  FROM [CAT1].[cms].[inp_claimsj_2013]
union SELECT 2014 as year ,[DESY_SORT_KEY],[CLAIM_NO], (isnull([ICD_DGNS_CD1],'')+'^'+      isnull([ICD_DGNS_CD2],'')+'^'+      isnull([ICD_DGNS_CD3],'')+'^'+      isnull([ICD_DGNS_CD4],'')+'^'+      isnull([ICD_DGNS_CD5],'')+'^'+      isnull([ICD_DGNS_CD6],'')+'^'+      isnull([ICD_DGNS_CD7],'')+'^'+      isnull([ICD_DGNS_CD8],'')+'^'+      isnull([ICD_DGNS_CD9],'')+'^'+      isnull([ICD_DGNS_CD10],'')+'^'+      isnull([ICD_DGNS_CD11],'')+'^'+      isnull([ICD_DGNS_CD12],'')+'^'+      isnull([ICD_DGNS_CD13],'')+'^'+      isnull([ICD_DGNS_CD14],'')+'^'+      isnull([ICD_DGNS_CD15],'')+'^'+      isnull([ICD_DGNS_CD16],'')+'^'+      isnull([ICD_DGNS_CD17],'')+'^'+      isnull([ICD_DGNS_CD18],'')+'^'+      isnull([ICD_DGNS_CD19],'')+'^'+      isnull([ICD_DGNS_CD20],'')+'^'+      isnull([ICD_DGNS_CD21],'')+'^'+      isnull([ICD_DGNS_CD22],'')+'^'+      isnull([ICD_DGNS_CD23],'')+'^'+      isnull([ICD_DGNS_CD24],'')+'^'+      isnull([ICD_DGNS_CD25],'')) as dxall  FROM [CAT1].[cms].[out_claimsj_2014]
union SELECT 2014 as year ,[DESY_SORT_KEY],[CLAIM_NO], (isnull([ICD_DGNS_CD1],'')+'^'+      isnull([ICD_DGNS_CD2],'')+'^'+      isnull([ICD_DGNS_CD3],'')+'^'+      isnull([ICD_DGNS_CD4],'')+'^'+      isnull([ICD_DGNS_CD5],'')+'^'+      isnull([ICD_DGNS_CD6],'')+'^'+      isnull([ICD_DGNS_CD7],'')+'^'+      isnull([ICD_DGNS_CD8],'')+'^'+      isnull([ICD_DGNS_CD9],'')+'^'+      isnull([ICD_DGNS_CD10],'')+'^'+      isnull([ICD_DGNS_CD11],'')+'^'+      isnull([ICD_DGNS_CD12],'')+'^'+      isnull([ICD_DGNS_CD13],'')+'^'+      isnull([ICD_DGNS_CD14],'')+'^'+      isnull([ICD_DGNS_CD15],'')+'^'+      isnull([ICD_DGNS_CD16],'')+'^'+      isnull([ICD_DGNS_CD17],'')+'^'+      isnull([ICD_DGNS_CD18],'')+'^'+      isnull([ICD_DGNS_CD19],'')+'^'+      isnull([ICD_DGNS_CD20],'')+'^'+      isnull([ICD_DGNS_CD21],'')+'^'+      isnull([ICD_DGNS_CD22],'')+'^'+      isnull([ICD_DGNS_CD23],'')+'^'+      isnull([ICD_DGNS_CD24],'')+'^'+      isnull([ICD_DGNS_CD25],'')) as dxall  FROM [CAT1].[cms].[inp_claimsj_2014]
union SELECT 2015 as year ,[DESY_SORT_KEY],[CLAIM_NO], (isnull([ICD_DGNS_CD1],'')+'^'+      isnull([ICD_DGNS_CD2],'')+'^'+      isnull([ICD_DGNS_CD3],'')+'^'+      isnull([ICD_DGNS_CD4],'')+'^'+      isnull([ICD_DGNS_CD5],'')+'^'+      isnull([ICD_DGNS_CD6],'')+'^'+      isnull([ICD_DGNS_CD7],'')+'^'+      isnull([ICD_DGNS_CD8],'')+'^'+      isnull([ICD_DGNS_CD9],'')+'^'+      isnull([ICD_DGNS_CD10],'')+'^'+      isnull([ICD_DGNS_CD11],'')+'^'+      isnull([ICD_DGNS_CD12],'')+'^'+      isnull([ICD_DGNS_CD13],'')+'^'+      isnull([ICD_DGNS_CD14],'')+'^'+      isnull([ICD_DGNS_CD15],'')+'^'+      isnull([ICD_DGNS_CD16],'')+'^'+      isnull([ICD_DGNS_CD17],'')+'^'+      isnull([ICD_DGNS_CD18],'')+'^'+      isnull([ICD_DGNS_CD19],'')+'^'+      isnull([ICD_DGNS_CD20],'')+'^'+      isnull([ICD_DGNS_CD21],'')+'^'+      isnull([ICD_DGNS_CD22],'')+'^'+      isnull([ICD_DGNS_CD23],'')+'^'+      isnull([ICD_DGNS_CD24],'')+'^'+      isnull([ICD_DGNS_CD25],'')) as dxall  FROM [CAT1].[cms].[out_claimsj_2015]
union SELECT 2015 as year ,[DESY_SORT_KEY],[CLAIM_NO], (isnull([ICD_DGNS_CD1],'')+'^'+      isnull([ICD_DGNS_CD2],'')+'^'+      isnull([ICD_DGNS_CD3],'')+'^'+      isnull([ICD_DGNS_CD4],'')+'^'+      isnull([ICD_DGNS_CD5],'')+'^'+      isnull([ICD_DGNS_CD6],'')+'^'+      isnull([ICD_DGNS_CD7],'')+'^'+      isnull([ICD_DGNS_CD8],'')+'^'+      isnull([ICD_DGNS_CD9],'')+'^'+      isnull([ICD_DGNS_CD10],'')+'^'+      isnull([ICD_DGNS_CD11],'')+'^'+      isnull([ICD_DGNS_CD12],'')+'^'+      isnull([ICD_DGNS_CD13],'')+'^'+      isnull([ICD_DGNS_CD14],'')+'^'+      isnull([ICD_DGNS_CD15],'')+'^'+      isnull([ICD_DGNS_CD16],'')+'^'+      isnull([ICD_DGNS_CD17],'')+'^'+      isnull([ICD_DGNS_CD18],'')+'^'+      isnull([ICD_DGNS_CD19],'')+'^'+      isnull([ICD_DGNS_CD20],'')+'^'+      isnull([ICD_DGNS_CD21],'')+'^'+      isnull([ICD_DGNS_CD22],'')+'^'+      isnull([ICD_DGNS_CD23],'')+'^'+      isnull([ICD_DGNS_CD24],'')+'^'+      isnull([ICD_DGNS_CD25],'')) as dxall  FROM [CAT1].[cms].[inp_claimsj_2015]
union SELECT 2016 as year ,[DESY_SORT_KEY],[CLAIM_NO], (isnull([ICD_DGNS_CD1],'')+'^'+      isnull([ICD_DGNS_CD2],'')+'^'+      isnull([ICD_DGNS_CD3],'')+'^'+      isnull([ICD_DGNS_CD4],'')+'^'+      isnull([ICD_DGNS_CD5],'')+'^'+      isnull([ICD_DGNS_CD6],'')+'^'+      isnull([ICD_DGNS_CD7],'')+'^'+      isnull([ICD_DGNS_CD8],'')+'^'+      isnull([ICD_DGNS_CD9],'')+'^'+      isnull([ICD_DGNS_CD10],'')+'^'+      isnull([ICD_DGNS_CD11],'')+'^'+      isnull([ICD_DGNS_CD12],'')+'^'+      isnull([ICD_DGNS_CD13],'')+'^'+      isnull([ICD_DGNS_CD14],'')+'^'+      isnull([ICD_DGNS_CD15],'')+'^'+      isnull([ICD_DGNS_CD16],'')+'^'+      isnull([ICD_DGNS_CD17],'')+'^'+      isnull([ICD_DGNS_CD18],'')+'^'+      isnull([ICD_DGNS_CD19],'')+'^'+      isnull([ICD_DGNS_CD20],'')+'^'+      isnull([ICD_DGNS_CD21],'')+'^'+      isnull([ICD_DGNS_CD22],'')+'^'+      isnull([ICD_DGNS_CD23],'')+'^'+      isnull([ICD_DGNS_CD24],'')+'^'+      isnull([ICD_DGNS_CD25],'')) as dxall  FROM [CAT1].[cms].[out_claimsk_2016]
union SELECT 2016 as year ,[DESY_SORT_KEY],[CLAIM_NO], (isnull([ICD_DGNS_CD1],'')+'^'+      isnull([ICD_DGNS_CD2],'')+'^'+      isnull([ICD_DGNS_CD3],'')+'^'+      isnull([ICD_DGNS_CD4],'')+'^'+      isnull([ICD_DGNS_CD5],'')+'^'+      isnull([ICD_DGNS_CD6],'')+'^'+      isnull([ICD_DGNS_CD7],'')+'^'+      isnull([ICD_DGNS_CD8],'')+'^'+      isnull([ICD_DGNS_CD9],'')+'^'+      isnull([ICD_DGNS_CD10],'')+'^'+      isnull([ICD_DGNS_CD11],'')+'^'+      isnull([ICD_DGNS_CD12],'')+'^'+      isnull([ICD_DGNS_CD13],'')+'^'+      isnull([ICD_DGNS_CD14],'')+'^'+      isnull([ICD_DGNS_CD15],'')+'^'+      isnull([ICD_DGNS_CD16],'')+'^'+      isnull([ICD_DGNS_CD17],'')+'^'+      isnull([ICD_DGNS_CD18],'')+'^'+      isnull([ICD_DGNS_CD19],'')+'^'+      isnull([ICD_DGNS_CD20],'')+'^'+      isnull([ICD_DGNS_CD21],'')+'^'+      isnull([ICD_DGNS_CD22],'')+'^'+      isnull([ICD_DGNS_CD23],'')+'^'+      isnull([ICD_DGNS_CD24],'')+'^'+      isnull([ICD_DGNS_CD25],'')) as dxall  FROM [CAT1].[cms].[inp_claimsk_2016]
union SELECT 2017 as year ,[DESY_SORT_KEY],[CLAIM_NO], (isnull([ICD_DGNS_CD1],'')+'^'+      isnull([ICD_DGNS_CD2],'')+'^'+      isnull([ICD_DGNS_CD3],'')+'^'+      isnull([ICD_DGNS_CD4],'')+'^'+      isnull([ICD_DGNS_CD5],'')+'^'+      isnull([ICD_DGNS_CD6],'')+'^'+      isnull([ICD_DGNS_CD7],'')+'^'+      isnull([ICD_DGNS_CD8],'')+'^'+      isnull([ICD_DGNS_CD9],'')+'^'+      isnull([ICD_DGNS_CD10],'')+'^'+      isnull([ICD_DGNS_CD11],'')+'^'+      isnull([ICD_DGNS_CD12],'')+'^'+      isnull([ICD_DGNS_CD13],'')+'^'+      isnull([ICD_DGNS_CD14],'')+'^'+      isnull([ICD_DGNS_CD15],'')+'^'+      isnull([ICD_DGNS_CD16],'')+'^'+      isnull([ICD_DGNS_CD17],'')+'^'+      isnull([ICD_DGNS_CD18],'')+'^'+      isnull([ICD_DGNS_CD19],'')+'^'+      isnull([ICD_DGNS_CD20],'')+'^'+      isnull([ICD_DGNS_CD21],'')+'^'+      isnull([ICD_DGNS_CD22],'')+'^'+      isnull([ICD_DGNS_CD23],'')+'^'+      isnull([ICD_DGNS_CD24],'')+'^'+      isnull([ICD_DGNS_CD25],'')) as dxall  FROM [CAT1].[cms].[out_claimsk_2017]
union SELECT 2017 as year ,[DESY_SORT_KEY],[CLAIM_NO], (isnull([ICD_DGNS_CD1],'')+'^'+      isnull([ICD_DGNS_CD2],'')+'^'+      isnull([ICD_DGNS_CD3],'')+'^'+      isnull([ICD_DGNS_CD4],'')+'^'+      isnull([ICD_DGNS_CD5],'')+'^'+      isnull([ICD_DGNS_CD6],'')+'^'+      isnull([ICD_DGNS_CD7],'')+'^'+      isnull([ICD_DGNS_CD8],'')+'^'+      isnull([ICD_DGNS_CD9],'')+'^'+      isnull([ICD_DGNS_CD10],'')+'^'+      isnull([ICD_DGNS_CD11],'')+'^'+      isnull([ICD_DGNS_CD12],'')+'^'+      isnull([ICD_DGNS_CD13],'')+'^'+      isnull([ICD_DGNS_CD14],'')+'^'+      isnull([ICD_DGNS_CD15],'')+'^'+      isnull([ICD_DGNS_CD16],'')+'^'+      isnull([ICD_DGNS_CD17],'')+'^'+      isnull([ICD_DGNS_CD18],'')+'^'+      isnull([ICD_DGNS_CD19],'')+'^'+      isnull([ICD_DGNS_CD20],'')+'^'+      isnull([ICD_DGNS_CD21],'')+'^'+      isnull([ICD_DGNS_CD22],'')+'^'+      isnull([ICD_DGNS_CD23],'')+'^'+      isnull([ICD_DGNS_CD24],'')+'^'+      isnull([ICD_DGNS_CD25],'')) as dxall  FROM [CAT1].[cms].[inp_claimsk_2017])



select [DESY_SORT_KEY], count(claim_no) claimcount,dxall
into cms.zzsarahcohortp1
from s1
group by [DESY_SORT_KEY],dxall
having count(claim_no)>=3


       	